build:
  nodes:
    php82:
      environment:
        php: 8.2
        redis: false
      dependencies:
        before:
          - command: 'pecl channel-update pecl.php.net'
          - command: 'pecl install openswoole-25.2.0'
