build:
  nodes:
    php74:
      environment:
        php: 7.4
        redis: false
      dependencies:
        before:
          - command: 'pecl channel-update pecl.php.net'
          - command: 'pecl install openswoole-4.11.1'
